###
GET http://localhost:3000

### upload
POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=mi-boundary

--mi-boundary
Content-Disposition: form-data; name="foto"; filename="foto_vista.jpeg"
Content-Type: image/jpeg

< C:\Users\solis\OneDrive\Imágenes\1827714.jpg
--mi-boundary--

# text/plain: .txt.
# text/html: .html o .htm.
# text/css: .css.
# text/javascript: .js.
# application/json: JSON
# application/xml: .xml.
# application/zip: .zip.
# application/pdf: .pdf.
# application/sql: .sql.
# application/vnd.ms-excel: .xls o .xlsx.
# application/vnd.openxmlformats-officedocument.spreadsheetml.sheet: Documentos de Excel en formato OpenXML, para archivos .xlsx.
# application/msword: .doc.
# application/vnd.openxmlformats-officedocument.wordprocessingml.document: Documentos de Word en formato OpenXML, para archivos .docx.
# image/jpeg: .jpg o .jpeg.
# image/png: .png.
# image/gif: .gif.
# image/svg+xml: .svg.
# audio/mpeg: .mp3.
# audio/ogg: .ogg.
# video/mp4: .mp4.
# video/x-msvideo: .avi.